#!/bin/bash
#Load dotfiles
for file in ~/.config/bash/{bash_prompt,aliases,exports}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

shopt -s nocaseglob

PROMPT_DIRTRIM=2

# get current branch in git repo
function parse_git_branch() {
    BRANCH=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
    if [ "${BRANCH}" == "" ]
    then
        echo ""
    else
        echo " (${BRANCH})"
    fi
}

function multiline_prompt() {
    GREEN='\[\033[01;32m\]'
    BLUE='\[\033[01;34m\]'
    ORANGE='\[\033[38;5;202m\]'
    RESET='\[\033[00m\]'
    if [ "$color_prompt" = yes ]; then
        MODLINE="(${GREEN}\u@\h${RESET})-[${BLUE}\w${RESET}]${ORANGE}\`parse_git_branch\`${RESET}"
    else
        MODLINE="(\u@\h)-[\[\w\]]\`parse_git_branch\`"
    fi
    export PS1="$MODLINE
\$ "
    unset color_prompt force_color_prompt
}

bind 'set bell-style visible'

function bell() {
    "$@"
    tput bel
}

multiline_prompt

__tmux_sessionizer__() {
	$(~/.config/bash_scripts/tmux_sessionizer.sh > /dev/null)
}

__options__() {
    selected="$(cat ~/.config/bash_scripts/options.txt | fzf)"
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}${selected}${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
}

bind -m emacs-standard -x '"\C-f": __tmux_sessionizer__'
bind -x '"\C-gt":__options__'
bind '"\C-gd":"\C-u$(date +%Y%m%d%H%M)\e\C-e\C-a\C-y\C-e"'
